apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-media
spec:
  selector:
    matchLabels:
      app: api-media
  replicas: 1
  template:
    metadata:
      labels:
        app: api-media
    spec:
      imagePullSecrets:
        - name: regcred
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
        - name: api-media
          image: snikom1723/api-media:latest
---
apiVersion: v1
kind: Service
metadata:
  name: api-media
spec:
  selector:
    app: api-media
  ports:
    - name: api-port
      port: 4000
      nodePort: 30001
  type: NodePort
